version: "3"

services:
  blogDomain1:
    image: wordpress:5.1.1-apache
    depends_on:
      - dbDomain1
    environment:
      WORDPRESS_DB_HOST: dbContainerDomain1
      WORDPRESS_DB_USER: ZZZZZZZZZZZZ
      WORDPRESS_DB_PASSWORD: XXXXXXXXXXXXX
      WORDPRESS_DB_NAME: domain1
    labels:
      - traefik.backend=blogDomain1
      - traefik.frontend.rule=Host:www.domain1.com, domain1.com
      - traefik.docker.network=web
      - traefik.port=80
      - traefik.frontend.headers.SSLRedirect:true
      - traefik.frontend.headers.SSLForceHost:true
      - traefik.frontend.headers.SSLHost:www.domain1.com
      - traefik.frontend.redirect.regex:https://domain1.com([/](.*))*
      - traefik.frontend.redirect.replacement:https://www.domain1.com$${1}
    volumes:
      - ./domain1/wordpress_files:/var/www/html
    networks:
      - internal
      - web

  dbDomain1:
    image: mariadb:10.4.3
    environment:
      MYSQL_USER: ZZZZZZZZZZZZ 
      MYSQL_PASSWORD: XXXXXXXXXXXXX
      MYSQL_DATABASE: domain1
#      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    networks:
      - internal
    labels:
      - traefik.enable=false
    volumes:
      - ./domain1/datadir:/var/lib/mysql
      
  adminerDomain1:
    image: adminer:4.6.3-standalone
    labels:
      - traefik.backend=adminerDomain1
      - traefik.frontend.rule=Host:db-admin.domain1.com
      - traefik.docker.network=web
      - traefik.port=8080
    networks:
      - internal
      - web
    depends_on:
      - dbDomain1
      
networks:
  web:
    external: true
  internal:
    external: false
